### PR TITLE
Add CI endpoint to test site

### PR DESCRIPTION
**Pull request by nottrobin**

### CODE REVIEW

**Comment by b-m-f** [comment]
Wont this also pass if the http://localhost returns a 404?

**Comment by nottrobin** [comment]
I don't believe so. `curl --fail` should treat any status >= 400 as an error.

**Comment by b-m-f** [comment]
> I don't believe so. `curl --fail` should treat any status >= 400 as an error.

Oh, I missed that part!

**Comment by nottrobin** [comment]
@b-m-f:

``` bash
$ curl --fail http://httpbin.org/status/404 || echo "errored"
curl: (22) The requested URL returned error: 404 NOT FOUND
errored
```

**Pull request merged**
