### PR TITLE
Add global nav

### LINKED ISSUE #30: Add global nav
To match https://snapcraft.io. As requested by @therealjuan.

### PR DESCRIPTION
**Pull request by nottrobin**
Fixes #30 
Fixes https://github.com/canonicalltd/snap-squad/issues/794

QA
--

`./run`, look! Global nav!

### CODE REVIEW

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Comment by therealjuan** [comment]
I would like to have a conversation with @carlaberkers and @clagom before as I would like to include this as part of snapcraft.io so we can merge and deploy both things in parallel.

**Comment by nottrobin** [comment]
@therealjuan sounds good to me. Adding "Don't merge".

**Comment by therealjuan** [comment]
We agreed to include the global nav in snapcraft.io but without the login part as snapcraft.io should handle that for itself:

One image speaks better than a thousand words so...
docs

**Pull request merged**
